spring:
  application:
    name: musicproject
  datasource:
    url: jdbc:mysql://localhost:3306/musicproject?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

#mybatis??
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #??????????
    map-underscore-to-camel-case: true
